/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TosImport } from './routes/tos'
import { Route as MaintenanceImport } from './routes/maintenance'
import { Route as LobbyListImport } from './routes/lobby-list'
import { Route as FaqImport } from './routes/faq'
import { Route as FairnessImport } from './routes/fairness'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as LobbyCodeIndexImport } from './routes/lobby/$code/index'
import { Route as LobbyCodeRouletteImport } from './routes/lobby/$code/roulette'
import { Route as LobbyCodeBlackjackImport } from './routes/lobby/$code/blackjack'
import { Route as AuthVerifyEmailUserIdCodeIndexImport } from './routes/auth/verify-email/$userId/$code/index'
import { Route as AuthForgotPasswordNewUserIdResetCodeIndexImport } from './routes/auth/forgot-password/new/$userId/$resetCode/index'

// Create/Update Routes

const TosRoute = TosImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRoute,
} as any)

const MaintenanceRoute = MaintenanceImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRoute,
} as any)

const LobbyListRoute = LobbyListImport.update({
  id: '/lobby-list',
  path: '/lobby-list',
  getParentRoute: () => rootRoute,
} as any)

const FaqRoute = FaqImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const FairnessRoute = FairnessImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LobbyCodeIndexRoute = LobbyCodeIndexImport.update({
  id: '/lobby/$code/',
  path: '/lobby/$code/',
  getParentRoute: () => rootRoute,
} as any)

const LobbyCodeRouletteRoute = LobbyCodeRouletteImport.update({
  id: '/lobby/$code/roulette',
  path: '/lobby/$code/roulette',
  getParentRoute: () => rootRoute,
} as any)

const LobbyCodeBlackjackRoute = LobbyCodeBlackjackImport.update({
  id: '/lobby/$code/blackjack',
  path: '/lobby/$code/blackjack',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyEmailUserIdCodeIndexRoute =
  AuthVerifyEmailUserIdCodeIndexImport.update({
    id: '/auth/verify-email/$userId/$code/',
    path: '/auth/verify-email/$userId/$code/',
    getParentRoute: () => rootRoute,
  } as any)

const AuthForgotPasswordNewUserIdResetCodeIndexRoute =
  AuthForgotPasswordNewUserIdResetCodeIndexImport.update({
    id: '/auth/forgot-password/new/$userId/$resetCode/',
    path: '/auth/forgot-password/new/$userId/$resetCode/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqImport
      parentRoute: typeof rootRoute
    }
    '/lobby-list': {
      id: '/lobby-list'
      path: '/lobby-list'
      fullPath: '/lobby-list'
      preLoaderRoute: typeof LobbyListImport
      parentRoute: typeof rootRoute
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceImport
      parentRoute: typeof rootRoute
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosImport
      parentRoute: typeof rootRoute
    }
    '/lobby/$code/blackjack': {
      id: '/lobby/$code/blackjack'
      path: '/lobby/$code/blackjack'
      fullPath: '/lobby/$code/blackjack'
      preLoaderRoute: typeof LobbyCodeBlackjackImport
      parentRoute: typeof rootRoute
    }
    '/lobby/$code/roulette': {
      id: '/lobby/$code/roulette'
      path: '/lobby/$code/roulette'
      fullPath: '/lobby/$code/roulette'
      preLoaderRoute: typeof LobbyCodeRouletteImport
      parentRoute: typeof rootRoute
    }
    '/lobby/$code/': {
      id: '/lobby/$code/'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify-email/$userId/$code/': {
      id: '/auth/verify-email/$userId/$code/'
      path: '/auth/verify-email/$userId/$code'
      fullPath: '/auth/verify-email/$userId/$code'
      preLoaderRoute: typeof AuthVerifyEmailUserIdCodeIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password/new/$userId/$resetCode/': {
      id: '/auth/forgot-password/new/$userId/$resetCode/'
      path: '/auth/forgot-password/new/$userId/$resetCode'
      fullPath: '/auth/forgot-password/new/$userId/$resetCode'
      preLoaderRoute: typeof AuthForgotPasswordNewUserIdResetCodeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRoute
  '/fairness': typeof FairnessRoute
  '/faq': typeof FaqRoute
  '/lobby-list': typeof LobbyListRoute
  '/maintenance': typeof MaintenanceRoute
  '/tos': typeof TosRoute
  '/lobby/$code/blackjack': typeof LobbyCodeBlackjackRoute
  '/lobby/$code/roulette': typeof LobbyCodeRouletteRoute
  '/lobby/$code': typeof LobbyCodeIndexRoute
  '/auth/verify-email/$userId/$code': typeof AuthVerifyEmailUserIdCodeIndexRoute
  '/auth/forgot-password/new/$userId/$resetCode': typeof AuthForgotPasswordNewUserIdResetCodeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRoute
  '/fairness': typeof FairnessRoute
  '/faq': typeof FaqRoute
  '/lobby-list': typeof LobbyListRoute
  '/maintenance': typeof MaintenanceRoute
  '/tos': typeof TosRoute
  '/lobby/$code/blackjack': typeof LobbyCodeBlackjackRoute
  '/lobby/$code/roulette': typeof LobbyCodeRouletteRoute
  '/lobby/$code': typeof LobbyCodeIndexRoute
  '/auth/verify-email/$userId/$code': typeof AuthVerifyEmailUserIdCodeIndexRoute
  '/auth/forgot-password/new/$userId/$resetCode': typeof AuthForgotPasswordNewUserIdResetCodeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRoute
  '/fairness': typeof FairnessRoute
  '/faq': typeof FaqRoute
  '/lobby-list': typeof LobbyListRoute
  '/maintenance': typeof MaintenanceRoute
  '/tos': typeof TosRoute
  '/lobby/$code/blackjack': typeof LobbyCodeBlackjackRoute
  '/lobby/$code/roulette': typeof LobbyCodeRouletteRoute
  '/lobby/$code/': typeof LobbyCodeIndexRoute
  '/auth/verify-email/$userId/$code/': typeof AuthVerifyEmailUserIdCodeIndexRoute
  '/auth/forgot-password/new/$userId/$resetCode/': typeof AuthForgotPasswordNewUserIdResetCodeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/fairness'
    | '/faq'
    | '/lobby-list'
    | '/maintenance'
    | '/tos'
    | '/lobby/$code/blackjack'
    | '/lobby/$code/roulette'
    | '/lobby/$code'
    | '/auth/verify-email/$userId/$code'
    | '/auth/forgot-password/new/$userId/$resetCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/fairness'
    | '/faq'
    | '/lobby-list'
    | '/maintenance'
    | '/tos'
    | '/lobby/$code/blackjack'
    | '/lobby/$code/roulette'
    | '/lobby/$code'
    | '/auth/verify-email/$userId/$code'
    | '/auth/forgot-password/new/$userId/$resetCode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/fairness'
    | '/faq'
    | '/lobby-list'
    | '/maintenance'
    | '/tos'
    | '/lobby/$code/blackjack'
    | '/lobby/$code/roulette'
    | '/lobby/$code/'
    | '/auth/verify-email/$userId/$code/'
    | '/auth/forgot-password/new/$userId/$resetCode/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRoute
  FairnessRoute: typeof FairnessRoute
  FaqRoute: typeof FaqRoute
  LobbyListRoute: typeof LobbyListRoute
  MaintenanceRoute: typeof MaintenanceRoute
  TosRoute: typeof TosRoute
  LobbyCodeBlackjackRoute: typeof LobbyCodeBlackjackRoute
  LobbyCodeRouletteRoute: typeof LobbyCodeRouletteRoute
  LobbyCodeIndexRoute: typeof LobbyCodeIndexRoute
  AuthVerifyEmailUserIdCodeIndexRoute: typeof AuthVerifyEmailUserIdCodeIndexRoute
  AuthForgotPasswordNewUserIdResetCodeIndexRoute: typeof AuthForgotPasswordNewUserIdResetCodeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRoute,
  FairnessRoute: FairnessRoute,
  FaqRoute: FaqRoute,
  LobbyListRoute: LobbyListRoute,
  MaintenanceRoute: MaintenanceRoute,
  TosRoute: TosRoute,
  LobbyCodeBlackjackRoute: LobbyCodeBlackjackRoute,
  LobbyCodeRouletteRoute: LobbyCodeRouletteRoute,
  LobbyCodeIndexRoute: LobbyCodeIndexRoute,
  AuthVerifyEmailUserIdCodeIndexRoute: AuthVerifyEmailUserIdCodeIndexRoute,
  AuthForgotPasswordNewUserIdResetCodeIndexRoute:
    AuthForgotPasswordNewUserIdResetCodeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/fairness",
        "/faq",
        "/lobby-list",
        "/maintenance",
        "/tos",
        "/lobby/$code/blackjack",
        "/lobby/$code/roulette",
        "/lobby/$code/",
        "/auth/verify-email/$userId/$code/",
        "/auth/forgot-password/new/$userId/$resetCode/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx"
    },
    "/fairness": {
      "filePath": "fairness.tsx"
    },
    "/faq": {
      "filePath": "faq.tsx"
    },
    "/lobby-list": {
      "filePath": "lobby-list.tsx"
    },
    "/maintenance": {
      "filePath": "maintenance.tsx"
    },
    "/tos": {
      "filePath": "tos.tsx"
    },
    "/lobby/$code/blackjack": {
      "filePath": "lobby/$code/blackjack.tsx"
    },
    "/lobby/$code/roulette": {
      "filePath": "lobby/$code/roulette.tsx"
    },
    "/lobby/$code/": {
      "filePath": "lobby/$code/index.tsx"
    },
    "/auth/verify-email/$userId/$code/": {
      "filePath": "auth/verify-email/$userId/$code/index.tsx"
    },
    "/auth/forgot-password/new/$userId/$resetCode/": {
      "filePath": "auth/forgot-password/new/$userId/$resetCode/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
